### PR TITLE
Nintendo Switch support

### PR DESCRIPTION
**Pull request by AGraber**
Hi there, this set of changes adds support for building for Nintendo Switch using the devkitPro homebrew toolchain.

These two changes are mainly for Switch but they might improve compatibility with other exotic platforms too:
- Add `timiditycfg` config setting for modifying where TiMidity will look for a midi cfg file. TiMidity is the backend that is used on Switch by SDL_Mixer (as well as other platforms depending on backend availability) for playing midi files. Usually, it looks for `/etc/timidity/freepats.cfg` but that's not present on the Switch so it has to be configureable for it to look where appropiate.
- Add `SDL_LogError` call on `NACT::fatal` to facilitate debugging on platforms that don't implement `SDL_ShowSimpleMessageBox` (in this case the Switch).

The Switch-exclusive changes are:
- Added some CMake code to generate an NACP and NRO file with resources bundled into romfs (NRO is a custom format for the Switchm, preferred for homebrew - Switch can't use elf as is. NACP is a metadata file needed for NRO generation). This is only active on Switch, of course. The used CMake functions are provided by the Switch Homebrew Toolchain's CMake specs.
- Added icon for Switch
- Added GitHub actions Switch workflow.
- Added romfs init/exit code (to make the `romfs:/` path containing the resources available)

If you have any questions, please ask! If the Switch build ever breaks, don't hesitate to tag me whenever through an issue so I can take a look an it, although considering the multiplatform nature of the project it would be rare that only the Switch build breaks without other building too.

### CODE REVIEW

**Comment by AGraber** [comment]
This is how Rance 4.1 and Little Vampire looks like on it:

IMG_20221027_193953
IMG_20221027_213707

**Comment by kichikuou** [comment]
This looks great! Sadly I don't have a moddable Switch though.

Are you planning to write documentation on how to build and install (although it doesn't have to be in this repository)?

**Comment by AGraber** [comment]
Yeah, I forgot about that bit, I just added it. The steps are very similar to Linux other than the `pacman` devkitPro stuff. Relatively speaking, the amount of Switch-exclusive code is tiny as well, because of all the Android/Emscripten support already doing the legwork for multiplatform.

The GitHub Actions workflow file also takes care of building for Switch already, just a few seconds longer than the Linux build.

**Comment by kichikuou** [comment]
Thanks!

**Pull request merged**
